import Head from "next/head";
import Image from "next/image";

import AddTask from "@/components/AddTask";
import TaskList from "@/components/TaskList";
import backgroundImage from "@/assets/images/image.webp";
import profile from "@/assets/images/profile.jpg";

export default function Home() {
  return (
    <>
      <Head>
        <title>TODO List</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        data-testid="main"
        className="gap-7 grid place-content-center w-screen h-screen "
      >
        <div
          data-testid="background"
          className="-z-10 absolute inset-0 blur-[2px]"
        >
          <Image
            src={backgroundImage}
            alt="american bridge"
            fill
            sizes="(max-width: 768px) 100vw,
              (max-width: 1200px) 50vw,
              33vw"
            className="object-center object-cover"
            priority
          />
          <div className="absolute inset-0 h-full w-full bg-gradient-to-b from-black/30 to-black/30" />
        </div>
        <div
          data-testid="profile"
          className="place-self-center overflow-hidden rounded-full h-28 w-28 border-4 border-white/40 drop-shadow-md"
        >
          <Image
            src={profile}
            height={300}
            width={300}
            alt="user avatar"
            className="object-center object-contain"
            priority
          />
        </div>
        <AddTask />
        <TaskList />
      </main>
    </>
  );
}
